package es.ull.simulation.hta.osdi.ontology;

import java.util.Arrays;
import java.util.OptionalDouble;
import org.semanticweb.owlapi.model.IRI;

import es.ull.simulation.hta.osdi.exceptions.MalformedOSDiModelException;
import es.ull.simulation.hta.osdi.exceptions.UnsupportedOSDiFeatureException;
import es.ull.simulation.utils.Statistics;

/**
 * A wrapper for probabilistic expressions defined in the ontology that can be used to generate random variates.
 * @author Iván Castilla Rodríguez
 */
public class ProbabilisticExpressionWrapper extends BaseModelItemWrapper {
    public static class SyntheticBuilder {
        private final IRI expressionIRI;
        private final ProbabilityDistributionExpressionType dist;
        private final ModelWrapper modelWrapper;
        private OptionalDouble scale = OptionalDouble.empty();
        private OptionalDouble offset = OptionalDouble.empty();
        private OptionalDouble expectedValue = OptionalDouble.empty();
        private OptionalDouble stdDeviation = OptionalDouble.empty();
        private final double[] parameterValues;

        public SyntheticBuilder(ModelWrapper modelWrapper, String name, ProbabilityDistributionExpressionType dist) {
            this(modelWrapper, IModelItemWrapper.getSyntheticIRI(name), dist);
        }
        public SyntheticBuilder(ModelWrapper modelWrapper, IRI sourceIRI, String name, ProbabilityDistributionExpressionType dist) {
            this(modelWrapper, IModelItemWrapper.getSyntheticIRIFrom(sourceIRI, name), dist);
        }
        public SyntheticBuilder(ModelWrapper modelWrapper, IRI syntheticExpressionIRI, ProbabilityDistributionExpressionType dist) {
            this.modelWrapper = modelWrapper;
            this.expressionIRI = syntheticExpressionIRI;
            this.dist = dist;
            this.parameterValues = new double[dist.getParameters().length];
            // Initialize parameter values with NaN to detect missing values later
            for (int i = 0; i < parameterValues.length; i++) {
                parameterValues[i] = Double.NaN;
            }   
        }
        public SyntheticBuilder withScale(double scale) {
            this.scale = OptionalDouble.of(scale);
            return this;
        }
        public SyntheticBuilder withOffset(double offset) {
            this.offset = OptionalDouble.of(offset);
            return this;
        }
        public SyntheticBuilder withExpectedValueAndStdDeviation(double expectedValue, double stdDeviation) {
            this.expectedValue = OptionalDouble.of(expectedValue);
            this.stdDeviation = OptionalDouble.of(stdDeviation);
            return this;
        }
        public SyntheticBuilder withParameterValues(double[] parameterValues) {
            if (parameterValues.length != this.parameterValues.length) {
                throw new IllegalArgumentException("Expected " + this.parameterValues.length + " parameter values, but got " + parameterValues.length);
            }
            for (int i = 0; i < parameterValues.length; i++) {
                this.parameterValues[i] = parameterValues[i];
            }
            return this;
        }
        public ProbabilisticExpressionWrapper build() {
            return new ProbabilisticExpressionWrapper(this.modelWrapper, this.expressionIRI, this.dist, this.parameterValues, this.scale, this.offset, this.expectedValue, this.stdDeviation);
        }
    }

	private final OSDiWrapper wrap;
	/**
	 * The scale factor for the probabilistic expression, i.e., the factor by which the random variate generated by the probability distribution should be multiplied to obtain the value of the parameter it characterizes.
	 */
	private OptionalDouble scale;
	/**
	 * The offset for the probabilistic expression, i.e., the value that should be added to the random variate generated by the probability distribution to obtain the value of the parameter it characterizes.
	 */
	private OptionalDouble offset;
	/**
	 * The expected value (typically, average) of the parameter characterized by the probabilistic expression, if it is defined in the model.
	 */
	private OptionalDouble expectedValue;
	/**
	 * The standard deviation of the parameter characterized by the probabilistic expression, if it is defined in the model.
	 */
	private OptionalDouble stdDeviation;
	/**
	 * The parameter values for the distribution that characterizes the probabilistic expression. The specific parameters included
	 *  in this array depend on the distribution type, but they typically include the parameters explicitly defined in the model 
	 * for the probabilistic expression, or computed from the expected value and standard deviation 
	 * if they are not explicitly defined in the model.
	 */
	private double[] parameterValues = null;
	/**
	 * The distribution that characterizes the probabilistic expression.
	 */
	private ProbabilityDistributionExpressionType dist;
	/**
	 * Indicates whether this probabilistic expression wrapper is synthetic (i.e., created programmatically and not directly based on an ontology individual) or not. Synthetic probabilistic expressions are created with all necessary information and do not depend on any other ontology item, so they can be set as ready immediately.
	 */
	private final boolean synthetic;

	public ProbabilisticExpressionWrapper(ModelWrapper modelWrapper, IRI probabilisticExpressionIRI) {
		super(modelWrapper, probabilisticExpressionIRI);
		this.wrap = modelWrapper.getOSDiWrapper();
		this.synthetic = false;
	}

	private ProbabilisticExpressionWrapper(ModelWrapper modelWrapper, IRI expressionIRI, ProbabilityDistributionExpressionType dist, double[] parameterValues, OptionalDouble scale, OptionalDouble offset, OptionalDouble expectedValue, OptionalDouble stdDeviation) {
        super(modelWrapper, expressionIRI);
		this.wrap = modelWrapper.getOSDiWrapper();
        setProbabilityDistribution(dist);
		this.parameterValues = parameterValues;
		this.offset = offset;
		this.scale = scale;
		this.expectedValue = expectedValue;
		this.stdDeviation = stdDeviation;
        // Synthetic probabilistic expressions are created with all necessary information and do not depend on any other ontology item, 
		// so they can be set as ready immediately. However, since they comprise a modified component of the model, they should be marked as dirty
        setStatus(Status.DIRTY);
		this.synthetic = true;
    }

	@Override
	public boolean isSynthetic() {
		return synthetic;
	}

    public static ProbabilisticExpressionWrapper buildNormalFromAverageAndSD(ModelWrapper modelWrapper, String name, double average, double stdDeviation) {
        return new SyntheticBuilder(modelWrapper, name, ProbabilityDistributionExpressionType.NORMAL)
            .withExpectedValueAndStdDeviation(average, stdDeviation)
			.withParameterValues(new double[] {average, stdDeviation})
            .build();
    }

    public static ProbabilisticExpressionWrapper buildNormalFromAverageAndCIs(ModelWrapper modelWrapper, String name, double average, double[] ci) {
        final double sd = Statistics.sdFrom95CI(ci);
        return new SyntheticBuilder(modelWrapper, name, ProbabilityDistributionExpressionType.NORMAL)
            .withExpectedValueAndStdDeviation(average, sd)
			.withParameterValues(new double[] {average, sd})
            .build();
    }

    public static ProbabilisticExpressionWrapper buildGammaFromAverageAndSD(ModelWrapper modelWrapper, String name, double average, double stdDeviation) {
        final double[] gammaParams = Statistics.gammaParametersFromNormal(average, stdDeviation);
        return new SyntheticBuilder(modelWrapper, name, ProbabilityDistributionExpressionType.GAMMA)
            .withParameterValues(gammaParams)
            .build();
    }

    public static ProbabilisticExpressionWrapper buildGammaFromAverageAndCIs(ModelWrapper modelWrapper, String name, double average, double[] ci) {
        final double sd = Statistics.sdFrom95CI(ci);
        final double[] gammaParams = Statistics.gammaParametersFromNormal(average, sd);
        return new SyntheticBuilder(modelWrapper, name, ProbabilityDistributionExpressionType.GAMMA)
            .withParameterValues(gammaParams)
            .build();
    }

    public static ProbabilisticExpressionWrapper buildBetaFromAverageAndSD(ModelWrapper modelWrapper, String name, double average, double stdDeviation) {
        final double []paramsBeta = Statistics.betaParametersFromNormal(average, stdDeviation);
        return new SyntheticBuilder(modelWrapper, name, ProbabilityDistributionExpressionType.BETA)
            .withParameterValues(paramsBeta)
            .build();
    }

    public static ProbabilisticExpressionWrapper buildBetaFromAverageAndCIs(ModelWrapper modelWrapper, String name, double average, double[] ci) {
		final double sd = Statistics.sdFrom95CI(ci);
		final double []paramsBeta = Statistics.betaParametersFromNormal(average, sd);
        return new SyntheticBuilder(modelWrapper, name, ProbabilityDistributionExpressionType.BETA)
            .withParameterValues(paramsBeta)
            .build();
    }

	@Override
	public void doInitialize() throws MalformedOSDiModelException, UnsupportedOSDiFeatureException {
		final IRI probabilisticExpressionIRI = getIndividualIRI();
		for (ProbabilityDistributionExpressionType distType : ProbabilityDistributionExpressionType.values()) {
			if (wrap.isInstanceOf(probabilisticExpressionIRI, distType.getClazz())) {
				this.dist = distType;
				break;
			}
		}
		if (dist == null && wrap.isInstanceOf(probabilisticExpressionIRI, OSDiClass.PROBABILITY_DISTRIBUTION_EXPRESSION)) {
			throw new MalformedOSDiModelException("Probabilistic expression " + probabilisticExpressionIRI + " is not an instance of any known probability distribution expression type.");
		}
		// TODO: Compute the values from the expected value and standard deviation if they are present and the individual does not explicitly defined the expected parameters
		this.parameterValues = dist.getParameterValues(wrap, probabilisticExpressionIRI);
		this.offset = wrap.getDoubleValue(probabilisticExpressionIRI, OSDiDataProperty.HAS_OFFSET_PARAMETER);
		this.scale = wrap.getDoubleValue(probabilisticExpressionIRI, OSDiDataProperty.HAS_SCALE_PARAMETER);
		this.expectedValue = wrap.getDoubleValue(probabilisticExpressionIRI, OSDiDataProperty.HAS_AVERAGE_PARAMETER);
		this.stdDeviation = wrap.getDoubleValue(probabilisticExpressionIRI, OSDiDataProperty.HAS_STANDARD_DEVIATION_PARAMETER);
	}

	@Override
	public void doPersist() throws MalformedOSDiModelException, UnsupportedOSDiFeatureException {
		final IRI probabilisticExpressionIRI = getIndividualIRI();
		wrap.createIndividual(dist.getClazz(), probabilisticExpressionIRI);
		if (offset.isPresent()) {
			wrap.assertDataProperty(probabilisticExpressionIRI, wrap.toIRI(OSDiDataProperty.HAS_OFFSET_PARAMETER), offset.getAsDouble());
		}
		if (scale.isPresent()) {
			wrap.assertDataProperty(probabilisticExpressionIRI, wrap.toIRI(OSDiDataProperty.HAS_SCALE_PARAMETER), scale.getAsDouble());
		}
		if (expectedValue.isPresent()) {
			wrap.assertDataProperty(probabilisticExpressionIRI, wrap.toIRI(OSDiDataProperty.HAS_AVERAGE_PARAMETER), expectedValue.getAsDouble());
		}
		if (stdDeviation.isPresent()) {
			wrap.assertDataProperty(probabilisticExpressionIRI, wrap.toIRI(OSDiDataProperty.HAS_STANDARD_DEVIATION_PARAMETER), stdDeviation.getAsDouble());
		}
		for (int i = 0; i < dist.getParameters().length; i++) {
			// Handle parameter persistence
			OSDiDataProperty paramProperty = dist.getParameters()[i];
			double paramValue = parameterValues[i];
			wrap.assertDataProperty(probabilisticExpressionIRI, wrap.toIRI(paramProperty), paramValue);
		}
	}

	/**
	 * Returns the distribution that characterizes the probabilistic expression.
	 * @return the distribution that characterizes the probabilistic expression.
	 */
	public ProbabilityDistributionExpressionType getProbabilityDistribution() {
		return dist;
	}

	/**
	 * Sets the distribution that characterizes the probabilistic expression.
	 * @param dist the distribution that characterizes the probabilistic expression.
	 */
	protected void setProbabilityDistribution(ProbabilityDistributionExpressionType dist) {
		this.dist = dist;
	}

	/**
	 * Returns the parameter values for the distribution that characterizes the probabilistic expression.
	 * @return An array of doubles representing the parameter values.
	 */
	public double[] getParameterValues() {
		return parameterValues;
	}
	
	/**
	 * Returns the scale factor for the probabilistic expression.
	 * @return The scale factor.
	 */
	public double getScale() {
		return scale.orElse(1.0);
	}

	/**
	 * Returns the offset for the probabilistic expression.
	 * @return The offset.
	 */
	public double getOffset() {
		return offset.orElse(0.0);
	}

	/**
	 * Returns the expected value (typically, average) of the parameter characterized by the probabilistic expression, if it is defined in the model.
	 * @return The expected value of the parameter characterized by the probabilistic expression, or an empty OptionalDouble if it is not defined in the model.
	 */
	public OptionalDouble getExpectedValue() {
		return expectedValue;
	}

	/**
	 * Returns the standard deviation of the parameter characterized by the probabilistic expression, if it is defined in the model.
	 * @return The standard deviation of the parameter characterized by the probabilistic expression, or an empty OptionalDouble if it is not defined in the model.
	 */
	public OptionalDouble getStdDeviation() {
		return stdDeviation;
	}

	@Override
	public String toString() {
		return dist.name() + "(" + Arrays.toString(parameterValues) + ")";
	}
}
