package es.ull.simulation.hta.osdi.decisiontree;

import java.util.Set;
import java.util.TreeSet;

import org.semanticweb.owlapi.model.OWLOntologyCreationException;

import es.ull.simulation.hta.MalformedSimulationModelException;
import es.ull.simulation.hta.osdi.ontology.ExperimentWrapper;
import es.ull.simulation.hta.osdi.ontology.ModelWrapper;
import es.ull.simulation.hta.osdi.ontology.OSDiWrapper;
import es.ull.simulation.hta.osdi.exceptions.MalformedOSDiModelException;
import es.ull.simulation.hta.osdi.exceptions.UnsupportedOSDiFeatureException;
import es.ull.simulation.hta.osdi.ontology.ParameterWrapper;
import es.ull.simulation.hta.outcomes.DisutilityCombinationMethod;
import es.ull.simulation.hta.params.ParameterGroup;

/**
 * A wrapper class that provides a basic implementation for the methods of a {@link Model}. 
 */
public abstract class BaseModel implements Model {
    /**
     * The wrapper for the OSDi ontology.
     */
	protected final OSDiWrapper wrap;
    /**
     * The model wrapper
     */
    private final ModelWrapper modelWrapper;
    /**
     * The experiment wrapper
     */
    private final ExperimentWrapper experiment;
    /**
     * The disutility combination method used in this model.
     * This method defines how disutilities are combined in the decision tree.
     */
    private final DisutilityCombinationMethod duCombinationMethod;
    /**
     * Root node of the decision tree. 
     * This node is generated by the {@link #createTree()} method and contains the branches for the screening and no screening interventions.
     */
    private ChoiceNode rootNode;

    /**
     * Constructor to initialize the HTATreeModelWrapper with the specified ontology wrapper.
     *
	 * @param experiment The experiment wrapper containing the ontology and experiment details.
     * @throws UnsupportedOSDiFeatureException 
     * @throws MalformedOSDiModelException 
     * @throws OWLOntologyCreationException If there is an error creating the ontology.
     */
    public BaseModel(ExperimentWrapper experiment) throws MalformedSimulationModelException, MalformedOSDiModelException, UnsupportedOSDiFeatureException {
        this.experiment = experiment;
        this.wrap = experiment.getOSDiWrapper();
        this.modelWrapper = experiment.getModelWrapper();
        // Initializes the combination method for disutilities
		this.duCombinationMethod = experiment.getDisutilityCombinationMethod();
        rootNode = null;
    }

    @Override
    public OSDiWrapper getOSDiWrapper() {
        return wrap;
    }

    @Override
    public ExperimentWrapper getExperimentWrapper() {
        return experiment;
    }
    
    @Override
    public ChoiceNode getTree() throws MalformedOSDiModelException, MalformedSimulationModelException, UnsupportedOSDiFeatureException {
        if (rootNode == null) {
            rootNode = createTree();
            if (rootNode == null) {
                throw new MalformedSimulationModelException("The decision tree model must have a root node.");
            }
            finishTree(rootNode);
        }
        return rootNode;
    }

    @Override
    public DisutilityCombinationMethod getDisutilityCombinationMethod() {
        return duCombinationMethod;
    }

    /**
     * Generates the tree according to the knowledge contained in the ontology. Returns the root node of the decision tree.
     * This method is invoked from the getTree method only once, to avoid generating the tree every time it is requested.
     *
     * @return The root choice node of the decision tree.
     * @throws MalformedOSDiModelException If the OSDi model is malformed.
     * @throws MalformedSimulationModelException If the simulation model is malformed.
     * @throws UnsupportedOSDiFeatureException If the model contains unsupported features, such as multiple screening interventions.
     */
    protected abstract ChoiceNode createTree() throws MalformedOSDiModelException, MalformedSimulationModelException, UnsupportedOSDiFeatureException;

    /**
     * Finishes the decision tree creation process.
     * This method traverses the decision tree and applies any final adjustments or calculations needed. It also ensures that all branches finalize in a payoff node.
     * @param successors The list of successors to finalize.
     * @throws MalformedSimulationModelException 
     * @throws UnsupportedOSDiFeatureException 
     */
    private void finishTree(DecisionTreeNode predecessor) throws MalformedSimulationModelException, UnsupportedOSDiFeatureException {
        for (BranchDestinationNode successor : predecessor.getSuccessors()) {
            if (!successor.isPayoff()) {
                finishTree(successor);
            } 
        }
        if (predecessor instanceof BranchDestinationNode) {
            BranchDestinationNode bdNode = (BranchDestinationNode) predecessor;
            BranchDestinationNode defaultSuccessor = bdNode.getDefaultSuccessor();
            if (defaultSuccessor != null) {
                if (!defaultSuccessor.isPayoff()) {
                    finishTree(defaultSuccessor);
                }
            }
        }
    }

    @Override
    public Set<ParameterWrapper> getParameters() throws MalformedOSDiModelException {
        return new TreeSet<>(modelWrapper.getParameters());
    }

    @Override
    public Set<ParameterWrapper> getParameters(ParameterGroup type)  throws MalformedOSDiModelException {
        Set<ParameterWrapper> parameters = new TreeSet<>();
        for (ParameterWrapper param : modelWrapper.getParameters()) {
            if (param.getParameterGroup() == type) {
                parameters.add(param);
            }
        }
        return parameters;
    }
}
